# 통합된 MCP 서버의 다양한 모드를 위한 Docker Compose 설정

version: '3.8'

services:
  # 개발용 MCP 서버 (모의 응답)
  mcp-server-dev:
    build: .
    command: python -m bridge.mcp_server_unified
    environment:
      BRIDGE_MCP_MODE: development
      BRIDGE_MCP_USE_SDK: "true"
      BRIDGE_MCP_ERROR_RECOVERY: "false"
      BRIDGE_MCP_SERVER_NAME: bridge-mcp-dev
      BRIDGE_MCP_VERSION: "1.0.0-dev"
    profiles: ["mcp-dev"]

  # 프로덕션용 MCP 서버 (실제 DB + 에러 복구)
  mcp-server-prod:
    build: .
    command: python -m bridge.mcp_server_unified
    environment:
      BRIDGE_MCP_MODE: production
      BRIDGE_MCP_USE_SDK: "true"
      BRIDGE_MCP_ERROR_RECOVERY: "true"
      BRIDGE_MCP_SERVER_NAME: bridge-mcp-prod
      BRIDGE_MCP_VERSION: "1.0.0"
      
      # 데이터베이스 연결 설정
      BRIDGE_POSTGRES_HOST: postgres
      BRIDGE_POSTGRES_PORT: 5432
      BRIDGE_POSTGRES_DB: bridge_prod
      BRIDGE_POSTGRES_USER: bridge_user
      BRIDGE_POSTGRES_PASSWORD: bridge_password
      
      BRIDGE_MYSQL_HOST: mysql
      BRIDGE_MYSQL_PORT: 3306
      BRIDGE_MYSQL_DB: bridge_prod
      BRIDGE_MYSQL_USER: bridge_user
      BRIDGE_MYSQL_PASSWORD: bridge_password
      
      BRIDGE_ELASTICSEARCH_HOST: elasticsearch
      BRIDGE_ELASTICSEARCH_PORT: 9200
      BRIDGE_ELASTICSEARCH_USE_SSL: "true"
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    profiles: ["mcp-prod"]

  # 실제 DB 연동 MCP 서버 (직접 JSON-RPC)
  mcp-server-real:
    build: .
    command: python -m bridge.mcp_server_unified
    environment:
      BRIDGE_MCP_MODE: real
      BRIDGE_MCP_USE_SDK: "false"
      BRIDGE_MCP_ERROR_RECOVERY: "true"
      BRIDGE_MCP_SERVER_NAME: bridge-mcp-real
      BRIDGE_MCP_VERSION: "1.0.0"
      
      # 데이터베이스 연결 설정
      BRIDGE_POSTGRES_HOST: postgres
      BRIDGE_POSTGRES_PORT: 5432
      BRIDGE_POSTGRES_DB: bridge_dev
      BRIDGE_POSTGRES_USER: bridge_user
      BRIDGE_POSTGRES_PASSWORD: bridge_password
      
      BRIDGE_MYSQL_HOST: mysql
      BRIDGE_MYSQL_PORT: 3306
      BRIDGE_MYSQL_DB: bridge_dev
      BRIDGE_MYSQL_USER: bridge_user
      BRIDGE_MYSQL_PASSWORD: bridge_password
      
      BRIDGE_ELASTICSEARCH_HOST: elasticsearch
      BRIDGE_ELASTICSEARCH_PORT: 9200
      BRIDGE_ELASTICSEARCH_USE_SSL: "false"
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    profiles: ["mcp-real"]

  # 간단한 MCP 서버 (모의 응답 + 직접 JSON-RPC)
  mcp-server-simple:
    build: .
    command: python -m bridge.mcp_server_unified
    environment:
      BRIDGE_MCP_MODE: mock
      BRIDGE_MCP_USE_SDK: "false"
      BRIDGE_MCP_ERROR_RECOVERY: "false"
      BRIDGE_MCP_SERVER_NAME: bridge-mcp-simple
      BRIDGE_MCP_VERSION: "1.0.0-simple"
    profiles: ["mcp-simple"]
